# Generated by Django 4.2 on 2025-08-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
