# Generated by Django 4.2 on 2025-08-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_razorpay_signature_order_stripe_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="stripe_session_id",
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
